from typing import Dict, Any

class PortfolioService:

    @classmethod
    def generate_portfolio_html(cls, data: Dict[str, Any], theme: str = "dark") -> str:
        name = data.get("full_name", "Developer Portfolio")
        summary = data.get("summary", "Software Engineer & AI Specialist")
        email = data.get("email", "")
        phone = data.get("phone", "")
        linkedin = data.get("linkedin", "")
        github = data.get("github", "")
        skills = data.get("skills", ["Python", "React", "FastAPI", "Machine Learning"])
        experience = data.get("experience", [])
        projects = data.get("projects", [])

        bg_color = "#0f172a" if theme == "dark" else "#f8fafc"
        text_color = "#f8fafc" if theme == "dark" else "#0f172a"
        card_bg = "#1e293b" if theme == "dark" else "#ffffff"
        accent_color = "#6366f1"

        skills_html = "".join([f'<span style="background:{accent_color}22; color:{accent_color}; border:1px solid {accent_color}44; padding:6px 12px; border-radius:20px; font-size:12px; font-weight:600; margin:4px; display:inline-block;">{s}</span>' for s in skills])

        exp_html = ""
        for exp in experience:
            role = exp.get("role", "Software Engineer")
            company = exp.get("company", "Tech Co")
            duration = exp.get("duration", "2024 - Present")
            exp_html += f'''
            <div style="background:{card_bg}; padding:20px; border-radius:12px; margin-bottom:16px; border:1px solid rgba(255,255,255,0.1);">
                <div style="display:flex; justify-content:space-between; align-items:center;">
                    <h3 style="margin:0; font-size:16px; color:{text_color};">{role}</h3>
                    <span style="font-size:12px; color:{accent_color}; font-weight:600;">{duration}</span>
                </div>
                <p style="margin:4px 0 0 0; font-size:14px; opacity:0.8;">{company}</p>
            </div>
            '''

        html_template = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name} — Interactive Portfolio</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background-color: {bg_color};
            color: {text_color};
            margin: 0;
            padding: 0;
            line-height: 1.6;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 20px;
        }}
        header {{
            text-align: center;
            padding: 60px 20px;
            background: linear-gradient(135deg, {accent_color}15 0%, transparent 100%);
            border-radius: 20px;
            margin-bottom: 40px;
        }}
        h1 {{ font-size: 36px; margin: 0 0 10px 0; }}
        p.subtitle {{ font-size: 16px; opacity: 0.8; max-width: 600px; margin: 0 auto 20px auto; }}
        .contacts {{ font-size: 14px; opacity: 0.9; }}
        .contacts a {{ color: {accent_color}; text-decoration: none; margin: 0 10px; font-weight: 600; }}
        section {{ margin-bottom: 40px; }}
        h2 {{ font-size: 22px; border-bottom: 2px solid {accent_color}; padding-bottom: 8px; margin-bottom: 20px; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{name}</h1>
            <p class="subtitle">{summary}</p>
            <div class="contacts">
                {f'<a href="mailto:{email}">Email</a>' if email else ''}
                {f'<a href="https://{linkedin}" target="_blank">LinkedIn</a>' if linkedin else ''}
                {f'<a href="https://{github}" target="_blank">GitHub</a>' if github else ''}
            </div>
        </header>

        <section>
            <h2>Technical Skills & Expertise</h2>
            <div>{skills_html}</div>
        </section>

        <section>
            <h2>Professional Work Experience</h2>
            {exp_html if exp_html else '<p style="opacity:0.6;">Work experience entries will appear here.</p>'}
        </section>

        <footer style="text-align:center; opacity:0.5; font-size:12px; margin-top:60px;">
            Generated by HireMind AI — AI Career Operating System
        </footer>
    </div>
</body>
</html>'''
        return html_template
