import os
import xml.sax.saxutils as saxutils
from typing import Any, Dict

from app.core.config import settings
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def sanitize_pdf_text(text: str) -> str:
    """Escapes XML tags and ensures safe string representation for ReportLab."""
    if not text:
        return ""
    # Safe escape for ReportLab XML parser
    clean = saxutils.escape(str(text))
    # Replace non-printable control characters
    return "".join(c if ord(c) >= 32 or c in "\n\r\t" else "" for c in clean)


class ReportService:
    @classmethod
    def generate_pdf_report(cls, analysis_data: Dict[str, Any], filename_prefix: str = "HireMind_Analysis") -> str:
        pdf_filename = f"{filename_prefix}_{analysis_data.get('resume_id', '1')}.pdf"
        output_path = os.path.join(settings.REPORTS_DIR, pdf_filename)

        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        styles = getSampleStyleSheet()

        # Custom Palette
        PRIMARY = colors.HexColor("#4F46E5")  # Indigo
        SECONDARY = colors.HexColor("#06B6D4")  # Cyan
        DARK_TEXT = colors.HexColor("#1F2937")
        LIGHT_BG = colors.HexColor("#F9FAFB")

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontSize=22,
            leading=26,
            textColor=PRIMARY,
            alignment=0,
            spaceAfter=10,
        )

        heading_style = ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontSize=14,
            leading=18,
            textColor=PRIMARY,
            spaceBefore=12,
            spaceAfter=6,
        )

        body_style = ParagraphStyle(
            "BodyDark",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=DARK_TEXT,
            spaceAfter=4,
        )

        story = []

        # Safe Sanitized Input Text
        safe_filename = sanitize_pdf_text(analysis_data.get("filename", "Resume.pdf"))
        safe_rating = sanitize_pdf_text(analysis_data.get("rating", "Good"))

        # Header Title
        story.append(Paragraph("<b>HireMind AI</b> — Executive Resume Intelligence Report", title_style))
        story.append(Paragraph(f"<b>Filename:</b> {safe_filename} | <b>Rating:</b> {safe_rating}", body_style))
        story.append(HRFlowable(width="100%", thickness=2, color=PRIMARY, spaceAfter=15))

        # Score Overview Table
        score = analysis_data.get("ats_score", 0.0)
        score_data = [
            [
                Paragraph("<b>ATS Compatibility Score</b>", body_style),
                Paragraph(f"<b>{score} / 100</b>", body_style),
            ],
            [
                Paragraph("<b>Performance Benchmark</b>", body_style),
                Paragraph(f"<b>{safe_rating}</b>", body_style),
            ],
        ]

        t = Table(score_data, colWidths=[250, 250])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
                    ("TEXTCOLOR", (0, 0), (-1, -1), DARK_TEXT),
                    ("PADDING", (0, 0), (-1, -1), 8),
                    ("LINEBELOW", (0, 0), (-1, -1), 1, colors.HexColor("#E5E7EB")),
                ]
            )
        )
        story.append(t)
        story.append(Spacer(1, 15))

        # Skills Found
        story.append(Paragraph("Detected Core Skills", heading_style))
        skills = [sanitize_pdf_text(s) for s in analysis_data.get("skills_found", [])]
        skills_str = ", ".join(skills) or "None detected"
        story.append(Paragraph(f"<b>Skills:</b> {skills_str}", body_style))
        story.append(Spacer(1, 10))

        # Strengths
        story.append(Paragraph("Key Strengths", heading_style))
        for st in analysis_data.get("strengths", []):
            story.append(Paragraph(f"• {sanitize_pdf_text(st)}", body_style))
        story.append(Spacer(1, 10))

        # Suggestions
        story.append(Paragraph("Actionable Improvement Recommendations", heading_style))
        for sg in analysis_data.get("suggestions", []):
            story.append(Paragraph(f"• {sanitize_pdf_text(sg)}", body_style))
        story.append(Spacer(1, 15))

        # Footer
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#D1D5DB"), spaceAfter=10))
        story.append(
            Paragraph(
                "<i>Generated by HireMind AI — AI-Powered Career Intelligence Platform</i>",
                ParagraphStyle("Footer", parent=body_style, fontSize=8, textColor=colors.gray),
            )
        )

        doc.build(story)
        return output_path
