"""initial_schema

Revision ID: 6d5b7f21117e
Revises: 
Create Date: 2026-08-01 14:37:06.410215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5b7f21117e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('resume_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_sections', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_revisions_content_hash'), 'resume_revisions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_resume_revisions_deleted_at'), 'resume_revisions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resume_revisions_id'), 'resume_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_resume_revisions_resume_id'), 'resume_revisions', ['resume_id'], unique=False)
    op.add_column('career_roadmaps', sa.Column('completed_steps', sa.JSON(), nullable=True))
    op.add_column('career_roadmaps', sa.Column('in_progress_steps', sa.JSON(), nullable=True))
    op.add_column('career_roadmaps', sa.Column('remaining_steps', sa.JSON(), nullable=True))
    op.add_column('career_roadmaps', sa.Column('completion_percentage', sa.Float(), nullable=True))
    op.add_column('career_roadmaps', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.add_column('career_roadmaps', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('career_roadmaps', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_career_roadmaps_deleted_at'), 'career_roadmaps', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_career_roadmaps_resume_id'), 'career_roadmaps', ['resume_id'], unique=False)
    op.add_column('coach_messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_coach_messages_deleted_at'), 'coach_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_coach_messages_user_id'), 'coach_messages', ['user_id'], unique=False)
    op.add_column('feedbacks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_feedbacks_deleted_at'), 'feedbacks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.add_column('interview_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_interview_sessions_deleted_at'), 'interview_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_interview_sessions_resume_id'), 'interview_sessions', ['resume_id'], unique=False)
    op.add_column('job_applications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('job_applications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_job_applications_deleted_at'), 'job_applications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_job_applications_tailored_resume_id'), 'job_applications', ['tailored_resume_id'], unique=False)
    op.create_index(op.f('ix_job_applications_user_id'), 'job_applications', ['user_id'], unique=False)
    op.add_column('job_descriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('job_descriptions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_job_descriptions_deleted_at'), 'job_descriptions', ['deleted_at'], unique=False)
    op.add_column('job_matches', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_job_matches_deleted_at'), 'job_matches', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_resume_id'), 'job_matches', ['resume_id'], unique=False)
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('resume_analyses', sa.Column('revision_id', sa.Integer(), nullable=True))
    op.add_column('resume_analyses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('resume_analyses', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_resume_analyses_deleted_at'), 'resume_analyses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resume_analyses_resume_id'), 'resume_analyses', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_analyses_revision_id'), 'resume_analyses', ['revision_id'], unique=False)
    op.create_foreign_key(None, 'resume_analyses', 'resume_revisions', ['revision_id'], ['id'])
    op.add_column('resume_builder_drafts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('resume_builder_drafts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_resume_builder_drafts_deleted_at'), 'resume_builder_drafts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resume_builder_drafts_user_id'), 'resume_builder_drafts', ['user_id'], unique=False)
    op.add_column('resumes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('resumes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('resumes', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resumes', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resumes', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_resumes_deleted_at'), 'resumes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.drop_column('resumes', 'uploaded_at')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.add_column('resumes', sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_deleted_at'), table_name='resumes')
    op.alter_column('resumes', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('resumes', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resumes', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('resumes', 'deleted_at')
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'created_at')
    op.drop_column('resumes', 'title')
    op.drop_index(op.f('ix_resume_builder_drafts_user_id'), table_name='resume_builder_drafts')
    op.drop_index(op.f('ix_resume_builder_drafts_deleted_at'), table_name='resume_builder_drafts')
    op.drop_column('resume_builder_drafts', 'deleted_at')
    op.drop_column('resume_builder_drafts', 'created_at')
    op.drop_constraint(None, 'resume_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_resume_analyses_revision_id'), table_name='resume_analyses')
    op.drop_index(op.f('ix_resume_analyses_resume_id'), table_name='resume_analyses')
    op.drop_index(op.f('ix_resume_analyses_deleted_at'), table_name='resume_analyses')
    op.alter_column('resume_analyses', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('resume_analyses', 'deleted_at')
    op.drop_column('resume_analyses', 'revision_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_column('notifications', 'deleted_at')
    op.drop_index(op.f('ix_job_matches_resume_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_deleted_at'), table_name='job_matches')
    op.drop_column('job_matches', 'deleted_at')
    op.drop_index(op.f('ix_job_descriptions_deleted_at'), table_name='job_descriptions')
    op.drop_column('job_descriptions', 'deleted_at')
    op.drop_column('job_descriptions', 'updated_at')
    op.drop_index(op.f('ix_job_applications_user_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_tailored_resume_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_deleted_at'), table_name='job_applications')
    op.drop_column('job_applications', 'deleted_at')
    op.drop_column('job_applications', 'updated_at')
    op.drop_index(op.f('ix_interview_sessions_resume_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_deleted_at'), table_name='interview_sessions')
    op.drop_column('interview_sessions', 'deleted_at')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_deleted_at'), table_name='feedbacks')
    op.drop_column('feedbacks', 'deleted_at')
    op.drop_index(op.f('ix_coach_messages_user_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_deleted_at'), table_name='coach_messages')
    op.drop_column('coach_messages', 'deleted_at')
    op.drop_index(op.f('ix_career_roadmaps_resume_id'), table_name='career_roadmaps')
    op.drop_index(op.f('ix_career_roadmaps_deleted_at'), table_name='career_roadmaps')
    op.drop_column('career_roadmaps', 'deleted_at')
    op.drop_column('career_roadmaps', 'updated_at')
    op.drop_column('career_roadmaps', 'streak_days')
    op.drop_column('career_roadmaps', 'completion_percentage')
    op.drop_column('career_roadmaps', 'remaining_steps')
    op.drop_column('career_roadmaps', 'in_progress_steps')
    op.drop_column('career_roadmaps', 'completed_steps')
    op.drop_index(op.f('ix_resume_revisions_resume_id'), table_name='resume_revisions')
    op.drop_index(op.f('ix_resume_revisions_id'), table_name='resume_revisions')
    op.drop_index(op.f('ix_resume_revisions_deleted_at'), table_name='resume_revisions')
    op.drop_index(op.f('ix_resume_revisions_content_hash'), table_name='resume_revisions')
    op.drop_table('resume_revisions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
